"""added location column to EOD model

Revision ID: 588edc5aa711
Revises: 26e40931454f
Create Date: 2025-11-19 11:39:09.841863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588edc5aa711'
down_revision = '26e40931454f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Enum('lake_charles', 'jennings', name='location_enum'), server_default='lake_charles', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
