"""biginteger on ticket number column

Revision ID: 81fe352a99c1
Revises: dfa1fd4cba5c
Create Date: 2025-12-01 11:19:58.921272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81fe352a99c1'
down_revision = 'dfa1fd4cba5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.alter_column('ticket_number',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.alter_column('ticket_number',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
