"""added stripe and ebay card columns to deductions

Revision ID: cdd43cc87b56
Revises: 81fe352a99c1
Create Date: 2025-12-31 12:31:14.964186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd43cc87b56'
down_revision = '81fe352a99c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ebay_card', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod', schema=None) as batch_op:
        batch_op.drop_column('ebay_card')
        batch_op.drop_column('stripe')

    # ### end Alembic commands ###
