"""added location column to Deduction model

Revision ID: dfa1fd4cba5c
Revises: 588edc5aa711
Create Date: 2025-11-19 12:06:09.758834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa1fd4cba5c'
down_revision = '588edc5aa711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Enum('lake_charles', 'jennings', name='location_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
